### ISSUE TITLE
Incase of Payment Failure, user not being redirected back to opencart site

### ISSUE THREAD

**Issue by Shikhar-Nahar** [Instamojo/Instamojo-Opencart-2.3.X#3]
When I attempted a failing/cancelled transaction in the sandbox site, the user is intimated that the transaction has failed at the instamojo gateway site and are not redirected back to the opencart site.

**Comment by ashwch** [comment]
@Shikhar-Nahar Could you please send an email to support@instamojo.com with your sandbox username?
